### ISSUE TITLE
May_24_2022: issue with duplicated name N A and PATH WHIZ databases

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMap_monthlyGenesetBuild#17]
GSEA threw an error while I was trying to upload Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt: duplicated entries. Some of the duplicate entries seem identical and some seem identical in the name but not in the genes.

GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#TRANSCRIPTION TRANSLATION%PATHWHIZ%PW000455
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#G-PROTEIN SIGNALING CASCADE%PATHWHIZ%PW000728
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#MUSCLE CONTRACTION%N A%MUSCLE CONTRACTION
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#STEROIDOGENESIS%SMPDB%SMP0000130
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#EXCITATORY NEUROTRANSMISSION%N A%EXCITATORY NEUROTRANSMISSION
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#APOPTOSIS%N A%APOPTOSIS
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#MORPHINE INHIBITION OF MU-TYPE OPIOID RECEPTOR%N A%MORPHINE INHIBITION OF MU-TYPE OPIOID RECEPTOR
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#HEAT SHOCK PROTEIN HSP 90-ALPHA DISSOCIATES FROM GLUCOCORTICOID RECEPTOR%N A%HEAT SHOCK PROTEIN HSP 90-ALPHA DISSOCIATES FROM GLUCOCORTICOID RECEPTOR
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#CYTOKINE GENE TRANSCRIPTION%N A%CYTOKINE GENE TRANSCRIPTION
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#DEGRANULATION%N A%DEGRANULATION
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#MAPK SIGNALING PATHWAY%N A%MAPK SIGNALING PATHWAY
GeneSets should have unique names. The lookup is case INsensitive. Found duplicate name: Human_GOBP_AllPathways_no_GO_iea_May_24_2022_symbol.gmt#PHOSPHATIDYLINOSITOL SIGNALING SYSTEM%N A%PHOSPHATIDYLINOSITOL SIGNALING SYSTEM

**Comment by risserlin** [comment]
Thanks for catching this so quickly.

duplicate pathways in Pathbank. Looks like all the duplicates are subpathways imbedded in a bunch of different pathways. turned off sub-pathways but they are still showing up. They aren't defined as sub-pathway. tried skipping over them using "Sub-pathway" that is put into the name field of the pathways but they are still being pulled in.
These pathways, name contains "Subpathway".  -- for just pathbank, check the name and filter out pathways that contain subpathway.  Gets rid of these redundant sub pathways.
(This probably wouldn't be an issue if all the Pathbank files were released in one file as opposed to individual files for each pathway. 
Pathway build of May 25, 2022 incorporates fix (pathway build form May 24, 2022 with the faulty pathbank files has been removed)
